### PR TITLE
PDO Implementation

### PR DESCRIPTION
**Pull request by AlexanderKaschta**
- Created error.php, which will be shown, if an error occurs
- Created Database.php, a singleton class, handling PDO instances
- Changed action_page.php to use PDO
- action_page.php will only insert data, if it is called with POST and the required values from the form. If these parameters aren't passed, you will be redirected to error.php
- Removed old code from action_page.php
- Added .htaccess to the include directory to allow access from the web only to action_page.php

### CODE REVIEW

**Comment by AlexanderKaschta** [comment]
Some comments:
1. The original config file in "inc/config.php" is still required and should work without a problem
2. .htaccess is only restricting file access via the web. All locals requests, like filesystem requests, have full access to the files inside the folder. PHP will still be able to use them.

**Comment by grheine** [comment]
hey, es gibt jetzt deutlich mehr Felder, die in die Datenbank übernommen werden müssen. Bei deinem Request, sind die noch nicht berücksichtigt. Willst du das vllt erst noch einbauen, bevor ich deine Änderungen übernehme? Du hast glaube ich deutlich mehr Ahnung, wie man so mit Git umgeht, als ich ^^ 

VG Greta

**Comment by grheine** [comment]
ich hab gerade eben noch das Feld Telefonnummer hinzugefügt. Brauchst du eigentlich den sql Code für das erzeugen der Datenbank? 
Meine Handynummer ist übrigens 015735131801, falls du irgendeinen Messenger wie Telegram hast.

**Comment by LeStahL** [comment]
> ich hab gerade eben noch das Feld Telefonnummer hinzugefügt. Brauchst du eigentlich den sql Code für das erzeugen der Datenbank?
> Meine Handynummer ist übrigens ********

@grheine I assume you doxed yourself unintentionally here - this repo is visible publicly, so anyone on the internet has now access to your phone number. You might want to edit the comment and remove the information.

**Comment by frcl** [comment]
@AlexanderKaschta PDO produces an error for some special unicode charaters

> Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x88'

Do you know how to get around this?

**Comment by LeStahL** [comment]
that char is above U+FFFF - MySQL can only handle these with special encoding; which would be utf8mb4.

[https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html)

Did not check, but assume this is the problem

**Comment by frcl** [comment]
Ok, it was my bad. I forgot to include the correct my.cnf into the test environment. This baffled me, because we already use utf8mb4 per default.

**Comment by grheine** [comment]
there occurs an error like 

Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'Message' at row 1 in /var/www/html/ophase/inc/action_page.php:88 Stack trace: #0 /var/www/html/ophase/inc/action_page.php(88):PDOStatement->execute() #1 {main} thrown in /var/www/html/ophase/inc/action_page.php on line 88

**Comment by LeStahL** [comment]
@grheine PR is closed, and this is kind of not in the scope of this PR, so I suggest using issues for this kind of conversation.
Link for convenience: https://github.com/grheine/Ophase/issues/new/choose

You can reference specific contributors in your issues by marking them in a comment, which will ensure they get a mail notification, should they have them enabled.

**Pull request merged**
